package com.education.InstitutionManagement.Service;

import com.education.InstitutionManagement.Repository.InstituteRepository;
import com.education.InstitutionManagement.entity.Institute;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

@Service
public class InstituteService {
    // This means to get the bean which is auto-generated by Spring,We will use it to handle the data
    @Autowired
    InstituteRepository myInstRepo;

    //	get all Institutions info
    public List<Institute> getAllInstitutions() {
        return myInstRepo.findAll();
    }

    // save an Institution
    public void saveInstitution(Institute myInst)
    {
        myInstRepo.save(myInst);
    }

    // get Institution by Id
    public Optional<Institute> getInstitutionById(Integer instId) {
        //find an Institution by id
        return myInstRepo.findById(instId);

    }

    //delete institution by Id
    public void deleteInstById(Integer instId) {
        //	find an Institute by id
        Optional<Institute> myInst = (Optional<Institute>) myInstRepo.findById(instId);
        //	if there is not an Institute, who has the id, throw the error.
        if (myInst == null) {
            throw new RuntimeException("Institution not found");
        }
        //	delete an Institute, which has the id from the database
        myInstRepo.deleteById(instId);
    }

}

