spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/testdb
    continue-on-error: 'true'
    initialize: 'true'
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: 'true'
      ddl-auto: create
springdoc:
  api-docs:
    groups:
      enabled: 'true'
  swagger-ui:
    path: /swagger-ui.html
server:
  port: '8081'




